name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build --tag malekinsat/shopping-service:latest .

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push malekinsat/shopping-service:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az --version
            az account show
      - name: Configure AKS access
        run: |
          az aks get-credentials --resource-group microservices-shopping-application --name microservices-cluster

      - name: Create ConfigMap
        run: |
          kubectl create configmap customers-config --from-env-file=.env.dev
          
      - name: Apply deployment
        run: |
          kubectl apply -f app-deployment.yaml
